/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HeaderNav: typeof import('./src/components/Header/HeaderNav.vue')['default']
    HeaderNav12: typeof import('./src/components/Header/HeaderNav12.vue')['default']
    HeaderSelect: typeof import('./src/components/Header/HeaderSelect.vue')['default']
    HeaderSelect12: typeof import('./src/components/Header/HeaderSelect12.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
  }
}
